version: '3.9'
networks:
  deploy-network:
    driver: bridge

services:
  webapi:
    container_name: api
    build:
      context: API
      dockerfile: Dockerfile
    ports:
      - "7205:7205"
    networks:
      - deploy-network
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtOptions__SecretKey=123456789987654321123456789987654321123456789987654321
      - JwtOptions__ExpiresMonths=6
      - EncryptionSettings__Key=s8v9x/A?D(G+KbPe
      - FileStorageSettings__UploadFolderPath=/app/UploadedFiles
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=Poly;User=sa;Password=Password!123;TrustServerCertificate=true;

  db:
    container_name: mssql_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!123
    ports:
      - "1433:1433"
    networks:
      - deploy-network
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local
